# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Informatica - Materiale didattico
description: >-
  Materiale didattico di informatica sotto forma di dispense, brevi manuali, esempi
  e una collezione di esercizi per classi di scuola secondaria superiore.

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: informatica
kramdown:
  toc_levels: "2,3"

# Just The Docs
heading_anchors: false
lang: "it"
gh_edit_link: true
gh_edit_link_text: "Modifica questa pagina su GitHub."
gh_edit_repository: "https://github.com/ragazzojp/informatica-superiori"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
callouts:
  highlight:
    color: green
  
# Exclude build and bundle files
# In addition, you can hide some topics
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
# Add directories to exclude after the ones above
